---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

I spent a significant amount of time on online sites such as https://search.r-project.org/CRAN/refmans/gt/html/tab_style.html where I got a more in depth understanding of the specific function: tab_style from the gt package. With that, I was able to write code for: **DVS-7: I show creativity in my tables.** Example 1 Challenge 9 Q9. I followed this similar process with other new tools we learned in class, and I believe that I have grown and challenged myself.

In addition, I have dedicated time to walk through Kaliegh and Eva outside of class to ensure that their questions are answered. As a proactive and patient team member in my group, I am always actively engaged in group work as I attend class and ensure that we finish assignments together after class, and that team members all have the same understanding of the topics by reviewing the assignment together. As a valuable group member, after each problem in the practice activity, I review the problem, going over: what the problem is asking, how we approached it, and discuss the result we got. This allows all members to be on the same page. Not only have I started interacting with my group partners in class, but I have also foster a friendship.
