---
title: "practice activity 4"
format: html
editor: visual
---

```{r}
library(readxl) 
library(tidyverse)


military <- read_xlsx(here::here("data", 
                                 "gov_spending_per_capita.xlsx"), 
                      sheet = "Share of Govt. spending", 
                      skip = 7, 
                      n_max = 190)
```

```{r}

military_clean <- military |>
 mutate(across(`1988`:`2019`, .fns = na_if, ". ."), 
        across(`1988`:`2019`, .fns = na_if, "xxx"))

  
```

```{r}
military_clean |>
mutate(across(`1988`:`2019`, .fns = as.numeric))

```

```{r}
cont_region <- read_xlsx(here::here("data",
                                    "gov_spending_per_capita.xlsx"), 
                      sheet = "Regional totals", 
                      skip = 14) |> 
  filter(Region != "World total (including Iraq)", 
         Region != "World total (excluding Iraq)")
```

```{r}
military_clean <- military_clean |> 
  anti_join(cont_region, by = c("Country" = "Region"))

military_clean |> 
  filter(if_all(.cols= `1988`:`2019`, .fns= is.na))
```

Part One Answer

Central america

Asia and Oceania

Middle East

Sub-Saharan Africa

```{r}
military_long <-military_clean |>
  pivot_longer(cols = `1988`:`2019`, names_to = "Year", values_to = "Spending")
```

```{r}
  ggplot(data = military_long, mapping = aes(x=Spending, y =Year, group = Year)) + 
    geom_point(color = "tomato", alpha = 1/10) + 
    geom_boxplot(outliner.shape = NA) 
```
