---
title: "practice activity 9.2 simulation"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(here)
library(dplyr)
```

# **Warm-up**

-   What is the 95th percentile for trumpet weight?

```{r}
qnif(p = .95, min = 1.5, max = 3.5)
```

-   What is the 10th percentile for trombone weight?

```{r}
qnorm(p = 0.1, mean = 4.6, sd = 0.8)
```

-   About what percent of trombones do you expect to be more than 5 pounds?

```{r}
dnorm(x = 5, mean = 4.6, sd = 0.8)
```

-   About what percent of reed instruments do you expect to be more than 5 pounds?

```{r}
dchisq(x = 5, df = 4)
```

-   Q5 Simulate 100 random trombone weights. How many of them were below 4 pounds?

```{r}
weight <- rnorm(n = 100, mean = 4.6, sd = 0.8)
sum(weight<4)
```

\
Catching a Con

```{r}
set.seed(1957)

music_man <- function(n_tromb, n_cor, n_reed){
  
  trombones <- rnorm(n_tromb, mean = 4.6, sd = 0.8)
  cornets <- runif(n_cor, min = 1.5, max = 3.5)
  reeds <- rchisq(n_reed, df = 4)
  
  return(sum(trombones) + sum(cornets) + sum(reeds))
}

my_weights <- map_dbl(.x = 1:1000, 
                      .f = ~ music_man(n_tromb = 76, n_cor = 110, n_reed = 1035)
                      ) 
sum(my_weights < 4532)
```
